version: '3.8'

services:
  activemq:
    image: webcenter/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ACTIVEMQ_USER = admin
      - ACTIVEMQ_PASSWORD = admin
    volumes:
      - activemq-data:/opt/activemq/data

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kinopoisk
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"

volumes:
  activemq-data:
