
CREATE TABLE film (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
                      description VARCHAR(255),
                      film_id BIGINT,
                      film_name VARCHAR(255),
                      rating FLOAT,
                      year INT
);